CREATE TABLE [dbo].[Person]
(
    [PersonId] INT NOT NULL IDENTITY(1, 1) PRIMARY KEY, 
    [UserId] INT NOT NULL,
    [FirstName] NVARCHAR(50) NOT NULL DEFAULT '', 
    [LastName] NVARCHAR(150) NOT NULL DEFAULT '', 
    [UpdatedBy] NVARCHAR(50) NOT NULL DEFAULT SUSER_SNAME(),
    [UpdatedDate] DATETIME2 NOT NULL DEFAULT SYSDATETIME(), 
    CONSTRAINT [FK_Person_User] FOREIGN KEY ([UserId]) REFERENCES [dbo].[User]([UserId]) ON DELETE CASCADE
)
GO

CREATE INDEX [IX_Person_UserId] ON [dbo].[Person] ([UserId])
